---
language: python
services: docker

env:
    - ANSIBLE_VERSION=latest
    - ANSIBLE_VERSION=2.9.8

install:
    - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible ; else pip install ansible==$ANSIBLE_VERSION; fi
    - pip install ansible-lint

script:
    - ansible-lint playbook.yml
    - ansible-playbook --version
    - ansible-playbook -i inventory playbook.yml
