version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker build -f test/Dockerfile -t my-drp-test . 
      - run:
          name: Docker run
          command: docker run --network=host --rm my-drp-test:latest --name my-drp-test
