version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker build my-drp-test . 
      - run:
          name: Docker run
          command: docker run my-drp-test:latest 
