---

- name: Update repositories
  apt:
    update_cache: yes

- name: Install packages
  apt:
    state: present
    name:
      - 'git'
      - 'git-core'
      - 'wget'
      - 'tree'
      - 'curl'
      - 'vim'
      - 'net-tools'
      - 'zsh'
      - 'tmux'
      - 'snapd'
      - 'python3-apt'
      - 'python3-pip'
      - 'ansible'
      - 'xz-utils'
      - 'net-tools'
      - 'fortune'

- name: Update all packages to the latest version
  apt:
    upgrade: full
