---

- name: update repositories
  apt:
    update_cache: yes

- name: install packages
  apt:
    state: present
    name:
      - 'git'
      - 'git-core'
      - 'wget'
      - 'tree'
      - 'curl'
      - 'vim'
      - 'net-tools'
      - 'zsh'
      - 'tmux'
      - 'snapd'
      - 'python3-apt'
      - 'ansible'
      - 'net-tools'

- name: upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: update all packages to the latest version
  apt:
    upgrade: dist
