---
- name: Install packages
  apt:
    state: present
    update_cache: True
    name:
      - 'git'
      - 'git-core'
      - 'wget'
      - 'tree'
      - 'curl'
      - 'firefox'
      - 'vim'
      - 'net-tools'
      - 'zsh'
      - 'tmux'
