
---

- name: Check if conda is installed
  shell: conda --version
  register: conda_check
  failed_when: conda_check.rc > 1
  changed_when: conda_check.rc == 1

- name: Download miniconda installation script
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /home/{{ user }}/SW/Miniconda3-latest-Linux-x86_64.sh
  when: conda_check.rc == 1

- name: Install miniconda
  shell: ./home/{{ user }}/SW/Miniconda3-latest-Linux-x86_64.sh -b -p /home/{{ user }}/miniconda3
  when: conda_check.rc == 1

- name: Add miniconda to the path
  blockinfile:
    path: "/home/{{ user }}/.zshrc"
    block: |
      # Minicoda
      export PATH=$HOME/miniconda3/bin:$PATH
      # >>> conda initialize >>>
      # !! Contents within this block are managed by 'conda init' !!
      __conda_setup="$('/home/arcones/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
      if [ $? -eq 0 ]; then
          eval "$__conda_setup"
      else
          if [ -f "/home/arcones/miniconda3/etc/profile.d/conda.sh" ]; then
              . "/home/arcones/miniconda3/etc/profile.d/conda.sh"
          else
              export PATH="/home/arcones/miniconda3/bin:$PATH"
          fi
      fi
      unset __conda_setup
      # <<< conda initialize <<<
  when: conda_check.rc == 1

