---

- name: Synchronization of public key
  copy:
    src: "/home/arcones/.ssh/common.pub"
    dest: "/home/{{ user }}/.ssh/common.pub"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  '0644'
  tags:
    - common
    - keys

- name: Synchronization of private key
  copy:
    src: "/home/arcones/.ssh/common"
    dest: "/home/{{ user }}/.ssh/common"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  '0600'
  tags:
    - common
    - keys

- name: Synchronization of known hosts
  copy:
    src: "/home/arcones/.ssh/known_hosts"
    dest: "/home/{{ user }}/.ssh/known_hosts"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  '0644'
  tags:
    - common
    - keys
