---

- name: Check if tfenv is installed
  stat:
    path: "/home/{{ user }}/.tfenv/bin/terraform"
  register: tfenv_existence
  tags:
    - common
    - tfenv

- name: Download tfenv
  git:
    repo: 'https://github.com/tfutils/tfenv.git'
    dest: "/home/{{ user }}/.tfenv"
    version: v2.0.0
  register: tfenv_installation
  tags:
    - common
    - tfenv

- name: Check tfenv installation
  command: /home/{{ user }}/.tfenv/bin/tfenv --version
  register: tfenv_version
  when: tfenv_installation is succeeded
  tags:
    - common
    - tfenv
