---

- name: Create common folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0744'
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "/home/{{ user }}/code/github"
    - "/home/{{ user }}/code/{{ company }}"
  tags:
    - common
    - user_config

- name: Copy wallpaper file
  copy:
    src: files/diverse_sponge_bob.jpg
    dest: "/home/{{ user }}/.diverse_sponge_bob_wallpaper.jpg"
    mode: "0744"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags:
    - common
    - user_config

- name: Set wallpaper
  become: yes
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ user }}/.diverse_sponge_bob_wallpaper.jpg'"
  tags:
    - common
    - user_config

- name: Copy monitors config
  copy:
    src: files/monitors.xml
    dest: "/home/{{ user }}/.config/monitors.xml"
  tags:
    - common
    - user_config

- name: Set favourite icons in the tray
  become: yes
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'org.gnome.Nautilus.desktop']"
  tags:
    - common
    - user_config

      #- name: Fetch all user's GitHub public repos
      #  command:
      #    cmd: "curl -s https://api.github.com/users/milanboers/repos | grep \"clone_url\" | awk '{print $2}'  | tr -d \" | tr -d ,"
      #  register: public_repos
      #  tags:
      #    - common
      #    - user_config
      #
      #  vars:
      #    github_repos: []
      #
      #- name: Print the security group names to the console.
      #  debug: var=public_repos
      #
      #- name: Build a list of all the github repos
      #  set_fact:
      #    github_repos: "{{ github_repos }} + [ '{{ item.group_name }}' ]"
      #  with_items: "{{ public_repos }}"
