---

- name: Set default shell for the user
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Create common folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0744'
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "/home/{{ user }}/code/arcones"
    - "/home/{{ user }}/SW"

- name: Copy wallpaper file
  copy:
    src: files/diverse_sponge_bob.jpg
    dest: "/home/{{ user }}/.diverse_sponge_bob_wallpaper.jpg"
    mode: "0744"
    owner: "{{ user }}"
    group: "{{ user }}"

- pip:
    name: psutil

- name: Set wallpaper
  become: yes
  become_user: "{{ user }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ user }}/.diverse_sponge_bob_wallpaper.jpg'"
