---

- name: create common folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0744'
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "/home/{{ user }}/code/arcones"
    - "/home/{{ user }}/SW"
