---

- name: create common folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0711'
  with_items:
    - "/home/{{ user }}/Code/Pers"
    - "/home/{{ user }}/Code/Prof"
    - "/home/{{ user }}/SW"
