---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - 'apacheds'
  tags:
    - zooplus
    - apache_ds

- name: Update all packages to the latest version
  apt:
    upgrade: full
  tags:
    - zooplus
    - apache_ds
