- name: Copy environment file
  copy:
    src: files/zooplus_conda_env.yml
    dest: "/home/{{ user }}/miniconda3/zooplus_conda_env.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0744"
