---

- name: Check if globalprotect client is installed
  stat:
    path: /usr/bin/globalprotect
  register: globalprotect_existence_check

- name: Copy globalprotect package
  copy:
    src: files/{{ globalprotect_package }}
    dest: /home/{{ user }}/SW/{{ globalprotect_package }}
  when: globalprotect_existence_check is failed

- name: Install globalprotect
  apt:
    deb: "/home/{{ user }}/SW/{{ globalprotect_package }}"
  when: globalprotect_existence_check is failed
