---

- name: Check if java is installed
  stat:
    path: /home/{{ user }}/.sdkman/candidates/java
  register: java_existence

- name: Install java 
  become: yes
  become_user: "{{ user }}"
  shell: "source /home/{{ user }}/.zshrc && sdk install java"
  args:
    executable: /bin/zsh
  register: java_installation_check
  when: not java_existence.stat.exists

- name: Check java installation
  become: yes
  become_user: "{{ user }}"
  shell: "source /home/{{ user }}/.zshrc && java --version"
  args:
    executable: /bin/zsh
  when: java_installation_check is succeeded
