---

- name: Check if teams is installed
  stat:
    path: /usr/bin/teams
  register: teams_existence

- name: Download teams package
  get_url:
    url: https://go.microsoft.com/fwlink/p/?linkid=2112886&clcid=0x409&culture=en-us&country=us
    dest: /home/{{ user }}/SW/teams.deb
  when: not teams_existence.stat.exists

- name: Install teams
  apt:
    deb: /home/{{ user }}/SW/teams.deb
  register: teams_installation_check
  when: not teams_existence.stat.exists

- name: Check teams installation
  command: teams
  when: teams_installation_check is succeeded
