---

- name: Add microsoft apt-key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags:
    - zooplus
    - teams

- name: Add teams repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
    state: present
  tags:
    - zooplus
    - teams

- name: Install team package
  apt:
    state: present
    update_cache: yes
    name:
      - 'teams'
  tags:
    - zooplus
    - teams
