---

- name: Check if teams is installed
  stat:
    path: /usr/bin/teams
  register: teams_existence_check

- name: Download teams package
  get_url:
    url: https://go.microsoft.com/fwlink/p/?linkid=2112886&clcid=0x409&culture=en-us&country=us
    dest: /home/{{ user }}/SW/teams.deb
  when: teams_existence_check is failed

- name: Install teams
  apt:
    deb: /home/{{ user }}/SW/teams.deb
  when: teams_existence_check is failed

