---

- name: check if teams is installed
  command: dpkg-query -W teams
  register: teams_check
  failed_when: teams_check.rc > 1
  changed_when: teams_check.rc == 1

- name: download teams package
  get_url:
    url: https://go.microsoft.com/fwlink/p/?linkid=2112886&clcid=0x409&culture=en-us&country=us
    dest: /home/{{ user }}/SW/teams.deb
  when: teams_check.rc == 1

- name: install globalprotect
  shell: dpkg -i /home/{{ user }}/SW/teams.deb
  when: teams_check.rc == 1
